---
title: "`r params$submission_id` | QAQC"
date: "`r lubridate::today()`"
output:
  html_document:
    toc: true
    toc-depth: 3
params:
  data_dir: C:\Users\jeffrey.walker\data\pacm
  submission_id: TEST_20230227
editor_options: 
  chunk_output_type: console
---

<style>
.main-container {
  max-width: 1200px !important;
}
.table {
 width: 0 !important;
}
</style>

```{r setup}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(sf)
library(glue)
library(janitor)
library(leaflet)
library(DT)

knitr::opts_chunk$set(echo = FALSE)
```

```{r}
data_dir <- params$data_dir
submission_id <- params$submission_id
x <- read_rds(file.path(data_dir, "processed", submission_id, glue("{submission_id}.rds")))

has_metadata <- nrow(x$metadata) > 0
valid_metadata <- !has_metadata | sum(x$metadata$n_errors) == 0 
has_detectiondata <- nrow(x$detectiondata) > 0
valid_detectiondata <- !has_detectiondata | sum(x$detectiondata$n_errors) == 0 
```

```text
data_dir: `r params$data_dir`
submission_id: `r params$submission_id`
created: `r lubridate::now(tz = "US/Eastern")`
```

```{r eval=(has_metadata & !valid_metadata), results="asis"}
cat('<div class="alert alert-danger">**Error**: Metadata contains', sum(x$metadata$n_errors), 'validation errors</div>')
```

```{r eval=(has_detectiondata & !valid_detectiondata), results="asis"}
cat('<div class="alert alert-danger">**Error**: Detection data contains', sum(x$detectiondata$n_errors), 'validation errors</div>')
```

----

## Metadata

```{r results="asis"}
if (!has_metadata) {
  cat('<div class="alert alert-info">Submission does not contain any metadata files</div>\n')
}
```

```{r eval=(has_metadata)}
x_metadata <- x$metadata %>% 
  select(filename, parsed) %>% 
  unnest(parsed)
x$metadata %>% 
  select(filename, n_rows, n_errors) %>% 
  knitr::kable(col.names = c("Filename", "# Rows", "# Errors"), caption = "Metadata File Summary")
```

### Validation

```{r eval=(has_metadata), results="asis"}
if (!valid_metadata) {
  cat('<div class="alert alert-danger">Metadata contains', sum(x$metadata$n_errors), 'validation errors.</div>')
} else {
  cat('<div class="alert alert-info">No validation errors</div>')
}
```

```{r eval=(has_metadata & !valid_metadata)}
x_metadata_validation_errors <- x$metadata %>% 
  select(filename, validation_errors) %>% 
  unnest(validation_errors)
knitr::kable(tabyl(x_metadata_validation_errors, name), caption = "Validation Error Summary")
```

```{r eval=(has_metadata & !valid_metadata), results="asis"}
cat("First 10 rows with validation errors (see `errors` column)")
```

```{r eval=(has_metadata & !valid_metadata)}
x_metadata_validation_errors %>% 
  group_by(filename, row) %>% 
  summarise(errors = str_c(unique(name), sep = ","), .groups = "drop") %>% 
  arrange(filename, row) %>% 
  left_join(x_metadata, by = c("filename", "row")) %>% 
  datatable()
```

### Map

Stationary platforms only

```{r eval=has_metadata}
x_metadata %>% 
  filter(STATIONARY_OR_MOBILE == "STATIONARY") %>% 
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = "EPSG:4326") %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(label = ~htmltools::htmlEscape(UNIQUE_ID))
```

### Monitoring Periods

```{r eval=has_metadata}
#| echo: false
x_metadata %>% 
  ggplot() +
  geom_segment(aes(x = MONITORING_START_DATETIME, xend = MONITORING_END_DATETIME, y = UNIQUE_ID, yend = UNIQUE_ID)) +
  labs(x = "MONITORING_START_DATETIME to MONITORING_END_DATETIME") +
  theme_bw() +
  theme(plot.margin = unit(c(5, 5, 5, 5), units = "mm"))
```

### Summary Tables

```{r eval=has_metadata}
knitr::kable(tabyl(x_metadata, DATA_POC_AFFILIATION), caption = "DATA_POC_AFFILIATION")
knitr::kable(tabyl(x_metadata, SITE_ID, PROJECT), caption = "SITE_ID x PROJECT")
knitr::kable(tabyl(x_metadata, PLATFORM_TYPE, STATIONARY_OR_MOBILE), caption = "PLATFORM_TYPE x STATIONARY_OR_MOBILE")
knitr::kable(tabyl(x_metadata, INSTRUMENT_TYPE), caption = "INSTRUMENT_TYPE")
knitr::kable(tabyl(x_metadata, SAMPLING_RATE_HZ), caption = "SAMPLING_RATE_HZ")
```

### Dataset

```{r eval=has_metadata}
datatable(x_metadata)
```

----

## Detection Data

```{r results="asis"}
if (!has_detectiondata) {
  cat('<div class="alert alert-info">Submission does not contain any detection data files</div>\n')
}
```

```{r eval=(has_detectiondata)}
x_detectiondata <- x$detectiondata %>% 
  select(filename, parsed) %>% 
  unnest(parsed)
x_detectiondata_summary <- x_detectiondata %>% 
  group_by(filename, UNIQUE_ID, SPECIES) %>% 
  summarize(
    ANALYSIS_PERIOD_START_DATETIME = min(ANALYSIS_PERIOD_START_DATETIME),
    ANALYSIS_PERIOD_END_DATETIME = max(ANALYSIS_PERIOD_END_DATETIME),
    N_DETECTIONS = sum(ACOUSTIC_PRESENCE == "D"),
    N_ROWS = n(),
    .groups = "drop"
  )

x$detectiondata %>% 
  select(filename, n_rows, n_errors) %>% 
  knitr::kable(col.names = c("Filename", "# Rows", "# Errors"), caption = "Detection Data File Summary")
```

### Validation

```{r eval=(has_detectiondata), results="asis"}
if (!valid_detectiondata) {
  cat('<div class="alert alert-danger">Detection data contains', sum(x$detectiondata$n_errors), 'validation errors.</div>')
} else {
  cat('<div class="alert alert-info">No validation errors</div>')
}
```

```{r eval=(has_detectiondata & !valid_detectiondata)}
x_detectiondata_validation_errors <- x$detectiondata %>% 
  select(filename, validation_errors) %>% 
  unnest(validation_errors)
knitr::kable(tabyl(x_detectiondata_validation_errors, name), caption = "Validation Error Summary")
```

```{r eval=(has_detectiondata & !valid_detectiondata)}
x_detectiondata_validation_errors %>% 
  group_by(filename, row) %>% 
  summarise(errors = str_c(unique(name), sep = ","), .groups = "drop") %>% 
  arrange(filename, row) %>% 
  left_join(x_detectiondata, by = c("filename", "row")) %>% 
  datatable()
```


### Summary Tables

```{r eval=has_detectiondata}
knitr::kable(tabyl(x_detectiondata, UNIQUE_ID, SPECIES), caption = "UNIQUE_ID x SPECIES")
knitr::kable(tabyl(x_detectiondata, SPECIES, ACOUSTIC_PRESENCE), caption = "SPECIES x ACOUSTIC_PRESENCE")
knitr::kable(tabyl(x_detectiondata, SPECIES, CALL_TYPE), caption = "SPECIES x CALL_TYPE")
```

### Dataset

Summary of each `UNIQUE_ID` and `SPECIES` including start/end of analysis period, number of detections (`ACOUSTIC_PRESENCE='P'`) and total number of rows.

```{r eval=has_detectiondata}
datatable(x_detectiondata_summary)
```
