default:
  files:
    root: "~/Dropbox/Work/nefsc/data"
    moored:
      metadata: "moored/20221103/Moored_metadata_2022-11-03.csv"
      detection: "moored/20221103/Moored_detection_data_2022-11-03.csv"
    glider:
      metadata: "glider/20221103/Glider_metadata_2022-11-03.csv"
      detection: "glider/20221103/Glider_detection_data_2022-11-03.csv"
    towed:
      metadata: "towed/Towed_Array_effort_Walker_Website_Daily_Resolution.xlsx"
      tracks: "towed/tracks"
      detections: "towed/detections"
    dfo:
      metadata: "dfo/DFOCA_METADATA_20211124.csv"
      detections: "dfo/detections"
